name: docker image build and push
on: [push]
jobs:

#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          platforms: linux/amd64,linux/arm64
#          tags: dockerchun/dockertips:latest

   deploy:
     runs-on: ubuntu-latest
#     needs: build
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: deploy to aws
         run: |
           cd ansible/
           pip install ansible
           echo "current directory is `pwd`"
           echo "current user is `whoami`"
           echo "list current directory `ls`"
           chmod 600 tokyo_2023.pem
           echo "list key file `ls -l tokyo_2023.pem`"
           echo `cat ~/.ssh/known_hosts`
           ansible-playbook -i hosts deploy.yml
